---
title: "OE regeneration and differentiation HBC heatmaps"
author: "Russell Fletcher, Diya Das"
date: '`r Sys.Date()`'
output:
html_document:
code_folding: hide
toc: yes
toc_float: yes
fig_width: 10
fig_height: 10
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE,include=FALSE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=FALSE, results="hide")

library(slingshot); library(clusterExperiment); library(RColorBrewer); library(rgl); library(rglwidget); library(R.utils); library(Rtsne); library(scales)
NMF::nmf.options(grid.patch=TRUE)##put anywhere in the script to remove first (blank) page of heatmap pdfs

expt_str <- "oeHBCregendiff"
clust_dir <- file.path("../output/clust", expt_str)
viz_dir <- file.path("../output/viz", expt_str)
DE_dir <- file.path("../output/DE", expt_str)

cc <- c(brewer.pal(8,"Dark2")[-c(2,3,5)],brewer.pal(12,"Paired")[c(1,2,8,10,9)],brewer.pal(12,"Set3")[c(7,8,12)], brewer.pal(8, "Pastel2")[8], brewer.pal(11,"BrBG")[11], brewer.pal(11,"PiYG")[1], "cyan", "darkblue","darkorchid2", "brown1", "springgreen1", "deepskyblue4", "darkolivegreen","antiquewhite2","azure", "cornflowerblue","blue","chartreuse","darkolivegreen3","darkorange3","deeppink4","darkred","darksalmon")
colpalH <- cc[c(26,14,12,29,1,3,6)]
cole <- c(brewer.pal(8, "Blues")[-c(1:2)], brewer.pal(5, "Reds"), brewer.pal(12, "Paired")[10])

#####-----oeHBCregendiff matrix
load(file=file.path(clust_dir, paste0(oeHBCregendiff, "_none_fq_ruv1_nobio_nobatch_hier_final_clusters.Rda")))
oeHBCregendiff_Mat <- transform(cmobj2)
```

###Pairwise DE, selecting comparison between activated HBCs (cl5) and transitional HBCs (cl19)
```{r pairwiseDE}
######------DE genes for heatmap

#####-----DE with limma voom on post-SCONE normalized counts; note that I add 0.5 and voom will add 0.5 more - #####otherwise, there are issues with normalized counts with values < -0.5.

pairsDEallv <-getBestFeatures(assay(cmobj2)+0.5, cmobj2@clusterMatrix[,1], contrastType="Pairs", number=Inf, contrastAdj="All", p.value=1, isCount=TRUE)
write.table(pairsDEallv, file.path(DE_dir, paste0(expt_str, "_pairs_all_voom.txt")), quote=FALSE, sep="\t")

#####-----To compare the regeneration HBC activated cluster (cl5) to the p63 cKO differentiation HBC transition cluster (cl19)

cl5vscl19 <- pairsDEallv[pairsDEallv$Contrast == "X19-X5",]
cl5vscl19 <- cl5vscl19[cl5vscl19$adj.P.Val < 0.01 & abs(cl5vscl19$logFC) > 1, ]

save(cl5vscl19, file = file.path(DE_dir, paste0(expt_str, "_pairsDE_cl5Vscl19.Rda")))
write.table(cl5vscl19, file.path(DE_dir, paste0(expt_str, "pairsDEcl5v19.txt")), quote=FALSE, sep="\t")

HBCdePairs <- as.character(droplevels(cl5vscl19[1:50,4]))

```

###Subsetting and preparing cluster assignments for plotting heatmaps
```{r dataPreparation}
oeHBCdiff_dir = "../output/clust/oeHBCdiff"
clus.labels_diff <- loadToEnv(file.path(oeHBCdiff_dir, paste0("oeHBCdiff_PCA.Rda")))[["clus.labels"]]
HBCdiffnames <- names(clus.labels_diff)[clus.labels_diff %in% c(1,8,5)]

oeHBCregen_dir <- "../output/clust/oeHBCregen"
clus.labels_regen <- loadToEnv(file.path(oeHBCregen_dir, paste0("EWT_PCA.Rda")))[["clus.labels"]]
clus.labels_regen <- factor(clus.labels_regen, levels=c(levels(clus.labels_regen),"H3"))
regennames <- names(clus.labels_regen)[clus.labels_regen %in% c(9,6,8,4,1)]
hbcsamples <- unique(c(HBCdiffnames, regennames))

# load combined data
cmobj <- get(load(file.path(clust_dir, paste0(oeHBCregendiff,"_none_fq_ruv1_nobio_nobatch_cm_hier_2.Rda"))))

hbc_obj <- cmobj[,match(hbcsamples,colnames(cmobj),nomatch = 0)]
hbc_clus.labels <- rep(0, ncol(hbc_obj)); names(hbc_clus.labels) <- colnames(hbc_obj)
hbc_clus.labels[regennames] <- clus.labels_regen[regennames]
hbc_clus.labels[hbc_clus.labels==9] <- "actHBC1"
hbc_clus.labels[hbc_clus.labels==6] <- "actHBC2"
hbc_clus.labels[hbc_clus.labels==8] <- "renewHBC1"
hbc_clus.labels[hbc_clus.labels==4] <- "renewHBC2"
hbc_clus.labels[hbc_clus.labels==1] <- "rest/renewedHBC"
table(hbc_clus.labels)

hbc_clus.labels[hbc_clus.labels==0] <- clus.labels_diff[names(hbc_clus.labels)[hbc_clus.labels==0]]

hbc_clus.labels[hbc_clus.labels==1] <- "rest/renewedHBC"
hbc_clus.labels[hbc_clus.labels==7] <- "transHBC1"
hbc_clus.labels[hbc_clus.labels==5] <- "transHBC2"

hbc_clus.labels <- factor(hbc_clus.labels)
cluster_ord <- c("rest/renewedHBC", "renewHBC2", "renewHBC1", "actHBC1","actHBC2","transHBC1","transHBC2")
intersect.labels <- intersect(colnames(oeHBCregendiff_Mat), names(hbc_clus.labels)) 
hbc_clus.labels2 <- hbc_clus.labels[intersect.labels] 
allClus.labels <- hbc_clus.labels2[order(match(hbc_clus.labels2, cluster_ord))] 
```

### Plotting heatmaps
```{r plottingHeatmaps}

breakw <- c(min(oeHBCregendiff_Mat), seq(0, quantile(oeHBCregendiff_Mat[oeHBCregendiff_Mat > 0], .99, na.rm = TRUE), length = 50), max(oeHBCregendiff_Mat)) 

###---Used the 50 pairwise DE genes for Figure 3
pdf(file=file.path(viz_dir, paste0(expt_str, "_HBC_pairwise50DE_heatmap.pdf")), height=8.5, width=11)
plotHeatmap(oeHBCregendiff_Mat[HBCdePairs,names(allClus.labels)], clusterSamples=F, clusterFeatures=T, breaks=breakw, sampleData=data.frame(clusters=allClus.labels, expt=colData(cmobj)[names(allClus.labels),2], batch=colData(cmobj)[names(allClus.labels),1]), clusterLegend=list(clusters=colpalH, expt=cole, batch=cc), main=paste(expt_str," HBCs by pair-wise DE")) 
dev.off()

```

