---
title: "Combined Regeneration and Differentiation scRNA-Seq Data Differential Expression"
author: "Russell Fletcher"
date: '`r Sys.Date()`'
output:
html_document:
code_folding: hide
toc: yes
toc_float: yes
fig_width: 10
fig_height: 10
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE,include=FALSE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=FALSE, results="hide")
library(clusterExperiment); library(RColorBrewer); library(limma)
NMF::nmf.options(grid.patch=TRUE)

expt_str <- "oeHBCregendiff"
clust_dir <- file.path("../output/clust", expt_str)
viz_dir <- file.path("../output/viz", expt_str)
DE_dir <- file.path("../output/DE", expt_str)

load(file=file.path(clust_dir, paste0(expt_str, "_none_fq_ruv1_nobio_nobatch_hier_final_clusters.Rda")))


```

```{r differentialExpression}

#####-----DE with limma voom on post-SCONE normalized counts; note that I add 0.5 and voom will add 0.5 more - #####otherwise, there are issues with normalized counts with values < -0.5.

pairsDEallv <-getBestFeatures(assay(cmobj2)+0.5, cmobj2@clusterMatrix[,1], contrastType="Pairs", number=Inf, contrastAdj="All", p.value=1, isCount=TRUE)
write.table(pairsDEallv, file.path(DE_dir, paste0(expt_str, "_pairs_all_voom.txt")), quote=FALSE, sep="\t")

```


```{r HBCactivatedVsHBCtransition}
#####-----To compare the regeneration HBC activated cluster (cl5) to the p63 cKO differentiation HBC transition cluster (cl19)

cl5vscl19 <- pairsDEallv[pairsDEallv$Contrast == "X19-X5",]
cl5vscl19 <- cl5vscl19[cl5vscl19$adj.P.Val < 0.01 & abs(cl5vscl19$logFC) > 1, ]

save(cl5vscl19, file = file.path(DE_dir, paste0(expt_str, "_pairsDE_cl5Vscl19.Rda")))
write.table(cl5vscl19, file.path(DE_dir, paste0(expt_str, "pairsDEcl5v19.txt")), quote=FALSE, sep="\t")

library(xlsx)
write.xlsx(cl5vscl19, file=file.path(DE_dir, paste0(expt_str, "cl5Vscl19DE.xlsx")), sheetName="cl5cl19pairwise")

```

