---
title: "oeHBCregen DE"
author: "Diya Das"
date: '`r Sys.Date()`'
output:
html_document:
code_folding: hide
toc: yes
toc_float: yes
fig_width: 10
fig_height: 10
---

```{r options, echo=TRUE, results="markup",message=FALSE, error=FALSE}
knitr::opts_chunk$set(cache=FALSE, fig.align="center", fig.width=10, error=TRUE,message=TRUE, echo=TRUE, warning=TRUE,results="markup")
library(clusterExperiment)
library(limma)
library(edgeR)
library(calibrate)
NMF::nmf.options(grid.patch=TRUE)
```

###Set-up and loading data
``` {r loading&set-up}

expt_str <- "oeHBCregenWTKO"
clust_dir <- file.path("../output/clust", expt_str)
DE_dir <- file.path("../output/DE", expt_str)

load(file.path(clust_dir, paste0(expt_str,"_lineageData2.Rda")))
load(file.path(clust_dir, paste0(expt_str,"_PCA.Rda")))
load(file.path(clust_dir, paste0(expt_str,"_cmmerged.Rda")))
```

```{r}
cell_id <- names(nlclusters2)[nlclusters2 %in% c(1,12,5,7,2,13)]
geno <- ifelse(grepl("SOX2CKO",expt),"KO","WT"); names(geno)<-names(expt)
hbc_mat <- nlm2[,cell_id]

cl_new <- as.character(nlclusters2)
cl_new[cl_new %in% c(2,7,13)] <- "HBC*"
cl_new <- factor(cl_new, levels=c(levels(nlclusters2),"HBC*"))
names(cl_new) <- names(nlclusters2)
cl2 <- paste0(cl_new[cell_id],"_",geno[cell_id])
names(cl2) <- cell_id
cl2 <- factor(cl2)

cl2_names <- c("1_KO","1_WT","12_KO","12_WT","5_KO","5_WT","HBC*_KO","HBC*_WT")
cl2_contrast <- c("X2-X1","X4-X3","X6-X5","X8-X7")
HBCpairs <- getBestFeatures(hbc_mat,cl2, contrastType="Pairs",number=Inf, p.value=0.05)

tmplist <- lapply(cl2_contrast, function(x){
  tmpsp <- unlist(strsplit(x,"-"))
  opposite_contrast <- paste0(tmpsp[2],"-",tmpsp[1])
  return(ifelse (x %in% levels(HBCpairs$Contrast),x, opposite_contrast))})
HBCpairs_sub <- HBCpairs[HBCpairs$Contrast %in% tmplist & abs(HBCpairs$logFC)>=1,]
HBCpairs_sub$logFC <- -1*HBCpairs_sub$logFC
HBCpairs_sub$Contrast <- sapply(HBCpairs_sub$Contrast, function(x){
  tmpsp <- unlist(strsplit(as.character(x),"-"))
  return( paste0(tmpsp[2],"-",tmpsp[1]))
} )
lookupt <- data.frame(cl2_contrast, cl_contrast_names=c('1_WT-1_KO',"12_WT-12_KO","5_WT-5_KO","HBC*_WT-HBC*_KO"))
write.table(HBCpairs_sub, file = paste0("../output/DE/",expt_str,"/",expt_str,'_PairsDETable.txt'), quote=FALSE, sep="\t")
contname <- c("1_WT-1_KO", "12_WT-12_KO","5_WT-5_KO","HBC*_WT-HBC*_KO" )

```

```{r}
glist <- unique(unlist(tapply(HBCpairs_sub$Feature, detab$Contrast, function(x) x[1:25])))

cl_ord <- cl_new[names(allclus.labels)]
cl_1 <- cl_ord[cl_ord==1]
cl_not1 <- cl_ord[cl_ord!=1]

ocol.pal_new <- c(col.pal[c(1,5,10)],"black")
pdf(file=file.path(DE_dir,paste0(expt_str, "_selectmarker_expt_25pairwiseDE_heatmap_UIHBCs", Sys.Date(), ".pdf")), width=7, height=4)
plotHeatmap(hbc_mat[glist[[1]],names(cl_1)], clusterSamples=FALSE,clusterFeatures=TRUE, breaks=breakv, sampleData=data.frame(clusters=cl_1, expt=expt[names(cl_1)], batch=batch[names(cl_1)]), clusterLegend=list(clusters=col.pal_new,expt=cole[c(1,7)],batch=bigPalette))
dev.off()


pdf(file=file.path(DE_dir,paste0(expt_str, "_selectmarker_expt_25pairwiseDE_heatmap_actHBCs_", Sys.Date(), ".pdf")), width=7, height=4)
plotHeatmap(hbc_mat[unique(unlist(glist[2:4])),names(cl_not1)], clusterSamples=FALSE,clusterFeatures=TRUE, breaks=breakv, sampleData=data.frame(clusters=cl_not1, expt=expt[names(cl_not1)], batch=batch[names(cl_not1)]), clusterLegend=list(clusters=col.pal_new[-1],expt=cole[-7],batch=bigPalette))
dev.off()
```

